name: Deploy de site html para uma instancia EC2


on:
  workflow_dispatch:

jobs:
  copy-html-ec2:
    environment: Development
    runs-on:  ubuntu-latest    
    
    steps:
    
       - uses: actions/checkout@v4

       - name: Run a multi-line script
         run: |
            ls
            echo ${{ secrets.SSH_SECRET_KEY }} > moongy-key.perm
            ssh -i moongy-key.perm ubuntu@ec2-44-223-24-163.compute-1.amazonaws.com -c "ls -all"
